Global:
  use_gpu: False
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./models/sagemaker_trained/
  save_epoch_step: 5
  eval_batch_step: [0, 1000]
  cal_metric_during_train: True
  save_inference_dir: ./models/sagemaker_trained/inference/
  use_visualdl: False
  infer_img: None
  character_dict_path: ../thai-letters/th_dict.txt
  character_type: thai
  max_text_length: 25
  infer_mode: False
  use_space_char: False
  distributed: False
  save_res_path: ./output/rec/predicts_thai_trained.txt
  pretrained_model: C:\Users\admin\Documents\sagemaker_thai-ocr\models\sagemaker_trained\best_model\model

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 96
  Head:
    name: CTCHead
    fc_decay: 0.00001

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 0.00003

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: thai-letters/datasets/converted/train_data_thai_paddleocr_0731_1604/train_data/rec/
    label_file_list:
      - thai-letters/datasets/converted/train_data_thai_paddleocr_0731_1604/train_data/rec/rec_gt_train.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: [image, label, length]
  loader:
    shuffle: True
    batch_size_per_card: 128
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: thai-letters/datasets/converted/train_data_thai_paddleocr_0731_1604/train_data/rec/
    label_file_list:
      - thai-letters/datasets/converted/train_data_thai_paddleocr_0731_1604/train_data/rec/rec_gt_val.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode:
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: [image, label, length]
  loader:
    shuffle: False
    batch_size_per_card: 128
    drop_last: False
    num_workers: 4
