Global:
  use_gpu: True
  epoch_num: 200
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/thai_rec_prod_output/
  save_epoch_step: 20
  eval_batch_step:
    - 0
    - 2000
  cal_metric_during_train: True
  pretrained_model: None
  checkpoints: None
  save_inference_dir: None
  use_visualdl: False
  infer_img: None
  character_dict_path: thai-letters\datasets\converted\train_data_thai_paddleocr_0731_1604/train_data/th_dict.txt
  character_type: thai
  max_text_length: 25
  infer_mode: False
  use_space_char: False
  distributed: True
  save_res_path: ./output/rec/predicts_svtr_tiny.txt
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0005
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3e-05
Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform: None
  Backbone:
    name: SVTRNet
    img_size:
      - 64
      - 256
    out_char_num: 25
    out_channels: 192
    patch_merging: Conv
    embed_dim:
      - 64
      - 128
      - 256
    depth:
      - 3
      - 6
      - 3
    num_heads:
      - 2
      - 4
      - 8
    mixer:
      - Local
      - Local
      - Local
      - Local
      - Local
      - Local
      - Global
      - Global
      - Global
      - Global
      - Global
      - Global
    local_mixer:
      - [7, 11]
      - [7, 11]
      - [7, 11]
    last_stage: True
    prenorm: False
  Head:
    name: CTCHead
    fc_decay: 1e-05
Loss:
  name: CTCLoss
PostProcess:
  name: CTCLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
Train:
  dataset:
    name: SimpleDataSet
    data_dir: thai-letters\datasets\converted\train_data_thai_paddleocr_0731_1604/train_data/rec/thai_data/
    ext_op_transform_idx: 1
    label_file_list:
      - thai-letters\datasets\converted\train_data_thai_paddleocr_0731_1604/train_data/rec/rec_gt_train.txt
    transforms:
      -
        DecodeImage:
          img_mode: BGR
          channel_first: False
      -
        RecConAug:
          prob: 0.5
          ext_data_num: 2
          image_shape:
            - 48
            - 320
            - 3
          max_text_length: 25
      -
        RecAug:
      -
        MultiLabelEncode:
      -
        RecResizeImg:
          image_shape:
            - 3
            - 64
            - 256
      -
        KeepKeys:
          keep_keys:
            - image
            - label
            - length
            - valid_ratio
  loader:
    shuffle: True
    batch_size_per_card: 256
    drop_last: True
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: thai-letters\datasets\converted\train_data_thai_paddleocr_0731_1604/train_data/rec/thai_data/
    label_file_list:
      - thai-letters\datasets\converted\train_data_thai_paddleocr_0731_1604/train_data/rec/rec_gt_val.txt
    transforms:
      -
        DecodeImage:
          img_mode: BGR
          channel_first: False
      -
        MultiLabelEncode:
      -
        RecResizeImg:
          image_shape:
            - 3
            - 64
            - 256
      -
        KeepKeys:
          keep_keys:
            - image
            - label
            - length
            - valid_ratio
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 256
    num_workers: 4
